# Generated by Django 5.2 on 2025-04-29 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('putih', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemeriksaan', models.DateField()),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('pengobatan', models.CharField(blank=True, max_length=100, null=True)),
                ('status_kesehatan', models.CharField(max_length=50)),
                ('catatan_tindak_lanjut', models.CharField(blank=True, max_length=100, null=True)),
                ('id_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan_medis_hijau', to='putih.hewan')),
                ('username_dh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan_medis_hijau_dokter', to='putih.dokterhewan')),
            ],
            options={
                'ordering': ['-tanggal_pemeriksaan'],
                'unique_together': {('id_hewan', 'tanggal_pemeriksaan')},
            },
        ),
    ]
