# Generated by Django 5.2 on 2025-04-29 12:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nama_depan', models.CharField(max_length=50)),
                ('nama_tengah', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_belakang', models.CharField(max_length=50)),
                ('no_telp', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_adopter', models.UUIDField(default=uuid.uuid4)),
                ('total_kontribusi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fasilitas',
            fields=[
                ('nama', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('jadwal', models.DateTimeField()),
                ('kapasitas_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('nama', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('luas_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kapasitas', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DokterHewan',
            fields=[
                ('pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('no_STR', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PelatihHewan',
            fields=[
                ('pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_staf', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Pengunjung',
            fields=[
                ('pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alamat', models.CharField(max_length=200)),
                ('tgl_lahir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PenjagaHewan',
            fields=[
                ('pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_staf', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='StafAdmin',
            fields=[
                ('pengguna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_staf', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Atraksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=100)),
                ('nama_atraksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.fasilitas')),
            ],
        ),
        migrations.CreateModel(
            name='Hewan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('spesies', models.CharField(max_length=100)),
                ('asal_hewan', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('status_kesehatan', models.CharField(max_length=50)),
                ('url_foto', models.URLField(max_length=225)),
                ('nama_habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.habitat')),
            ],
        ),
        migrations.CreateModel(
            name='Individu',
            fields=[
                ('nik', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16), django.core.validators.MaxLengthValidator(16)])),
                ('nama', models.CharField(max_length=100)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.adopter')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('npp', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(8)])),
                ('nama_organisation', models.CharField(max_length=100)),
                ('id_adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.adopter')),
            ],
        ),
        migrations.CreateModel(
            name='Wahana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peraturan', models.TextField()),
                ('nama_wahana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.fasilitas')),
            ],
        ),
        migrations.AddField(
            model_name='adopter',
            name='username_adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.pengunjung'),
        ),
        migrations.CreateModel(
            name='Berpartisipasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_fasilitas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.fasilitas')),
                ('id_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.hewan')),
            ],
            options={
                'unique_together': {('nama_fasilitas', 'id_hewan')},
            },
        ),
        migrations.CreateModel(
            name='Adopsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pembayaran', models.CharField(max_length=10)),
                ('tgl_mulai_adopsi', models.DateTimeField()),
                ('tgl_berhenti_adopsi', models.DateTimeField()),
                ('kontribusi_finansial', models.IntegerField()),
                ('id_adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.adopter')),
                ('id_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.hewan')),
            ],
            options={
                'unique_together': {('id_adopter', 'id_hewan', 'tgl_mulai_adopsi')},
            },
        ),
        migrations.CreateModel(
            name='JadwalPemeriksaanKesehatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_pemeriksaan_selanjutnya', models.DateTimeField()),
                ('freq_pemeriksaan_rutin', models.IntegerField()),
                ('id_hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.hewan')),
            ],
            options={
                'unique_together': {('id_hewan', 'tgl_pemeriksaan_selanjutnya')},
            },
        ),
        migrations.CreateModel(
            name='Pakan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jadwal', models.DateTimeField()),
                ('jenis', models.CharField(max_length=50)),
                ('jumlah', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.hewan')),
            ],
            options={
                'unique_together': {('hewan', 'jadwal')},
            },
        ),
        migrations.CreateModel(
            name='Spesialisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_spesialisasi', models.CharField(max_length=100)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.dokterhewan')),
            ],
            options={
                'unique_together': {('dokter', 'nama_spesialisasi')},
            },
        ),
        migrations.CreateModel(
            name='CatatanMedis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pemeriksaan', models.DateField()),
                ('diagnosis', models.CharField(blank=True, max_length=100, null=True)),
                ('pengobatan', models.CharField(blank=True, max_length=100, null=True)),
                ('status_kesehatan', models.CharField(max_length=100)),
                ('catatan_tindak_lanjut', models.CharField(blank=True, max_length=100, null=True)),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.hewan')),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.dokterhewan')),
            ],
            options={
                'unique_together': {('hewan', 'tanggal_pemeriksaan')},
            },
        ),
        migrations.CreateModel(
            name='JadwalPenugasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_penugasan', models.DateTimeField()),
                ('nama_atraksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.atraksi')),
                ('pelatih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.pelatihhewan')),
            ],
            options={
                'unique_together': {('pelatih', 'tgl_penugasan')},
            },
        ),
        migrations.CreateModel(
            name='Reserasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kunjungan', models.DateField()),
                ('jumlah_tiket', models.IntegerField()),
                ('nama_atraksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.atraksi')),
                ('username_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.pengunjung')),
            ],
            options={
                'unique_together': {('username_p', 'nama_atraksi', 'tanggal_kunjungan')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='adopter',
            unique_together={('username_adopter', 'id_adopter')},
        ),
        migrations.CreateModel(
            name='Memberi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jadwal', models.DateTimeField()),
                ('hewan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.hewan')),
                ('penjaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='putih.penjagahewan')),
            ],
            options={
                'unique_together': {('hewan', 'jadwal', 'penjaga')},
            },
        ),
    ]
